# Generated by Django 4.1.3 on 2022-11-16 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('properties', '0004_rename_client_areareservation_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='users.user')),
                ('reference_msg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference', to='inbox.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.Field()),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attach', to='inbox.message')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inbox.message')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property', to='properties.property')),
            ],
            bases=('inbox.message',),
        ),
    ]
