# Generated by Django 4.1.3 on 2022-11-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('properties', '0002_areareservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='areareservation',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='properties.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areareservation',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='responsible', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areareservation',
            name='comment',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
