# Generated by Django 4.1.3 on 2022-11-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_areareservation_area_areareservation_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areareservation',
            old_name='client',
            new_name='responsible',
        ),
    ]
